export const claudeColors = {
  primary: "#cc785c",
  "primary-active": "#a9583e",
  "primary-disabled": "#e6dfd8",
  ink: "#141413",
  body: "#3d3d3a",
  "body-strong": "#252523",
  muted: "#6c6a64",
  "muted-soft": "#8e8b82",
  hairline: "#e6dfd8",
  "hairline-soft": "#ebe6df",
  canvas: "#faf9f5",
  "surface-soft": "#f5f0e8",
  "surface-card": "#efe9de",
  "surface-cream-strong": "#e8e0d2",
  "surface-dark": "#181715",
  "surface-dark-elevated": "#252320",
  "surface-dark-soft": "#1f1e1b",
  "on-primary": "#ffffff",
  "on-dark": "#faf9f5",
  "on-dark-soft": "#a09d96",
  "accent-teal": "#5db8a6",
  "accent-amber": "#e8a55a",
  success: "#5db872",
  warning: "#d4a017",
  error: "#c64545",
} as const;

export const claudeTypography = {
  "display-xl": {
    fontFamily: 'var(--font-claude-serif), "Copernicus", "Tiempos Headline", "Cormorant Garamond", serif',
    fontSize: "64px",
    fontWeight: "400",
    lineHeight: "1.05",
    letterSpacing: "-1.5px",
    use: 'Homepage h1 ("Meet your thinking partner") — Copernicus serif',
  },
  "display-lg": {
    fontFamily: 'var(--font-claude-serif), "Copernicus", "Tiempos Headline", "Cormorant Garamond", serif',
    fontSize: "48px",
    fontWeight: "400",
    lineHeight: "1.1",
    letterSpacing: "-1px",
    use: "Section heads — Copernicus",
  },
  "display-md": {
    fontFamily: 'var(--font-claude-serif), "Copernicus", "Tiempos Headline", "Cormorant Garamond", serif',
    fontSize: "36px",
    fontWeight: "400",
    lineHeight: "1.15",
    letterSpacing: "-0.5px",
    use: "Sub-section heads, model names — Copernicus",
  },
  "display-sm": {
    fontFamily: 'var(--font-claude-serif), "Copernicus", "Tiempos Headline", "Cormorant Garamond", serif',
    fontSize: "28px",
    fontWeight: "400",
    lineHeight: "1.2",
    letterSpacing: "-0.3px",
    use: "Pricing tier names, callout headlines — Copernicus",
  },
  "title-lg": {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "22px",
    fontWeight: "500",
    lineHeight: "1.3",
    letterSpacing: "0",
    use: "Pricing plan size labels — StyreneB",
  },
  "title-md": {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "18px",
    fontWeight: "500",
    lineHeight: "1.4",
    letterSpacing: "0",
    use: "Feature card titles, intro paragraphs",
  },
  "title-sm": {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "16px",
    fontWeight: "500",
    lineHeight: "1.4",
    letterSpacing: "0",
    use: "Connector tile titles, list labels",
  },
  "body-md": {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "1.55",
    letterSpacing: "0",
    use: "Default running-text — StyreneB",
  },
  "body-sm": {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "1.55",
    letterSpacing: "0",
    use: "Footer body, fine-print",
  },
  caption: {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "13px",
    fontWeight: "500",
    lineHeight: "1.4",
    letterSpacing: "0",
    use: "Badge labels, captions",
  },
  "caption-uppercase": {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: "1.4",
    letterSpacing: "1.5px",
    use: 'Category tags, "NEW" badges',
  },
  code: {
    fontFamily: 'var(--font-claude-mono), "JetBrains Mono", ui-monospace, monospace',
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "1.6",
    letterSpacing: "0",
    use: "Code blocks — JetBrains Mono",
  },
  button: {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "14px",
    fontWeight: "500",
    lineHeight: "1.0",
    letterSpacing: "0",
    use: "Standard button labels",
  },
  "nav-link": {
    fontFamily: 'var(--font-claude-sans), "StyreneB", Inter, sans-serif',
    fontSize: "14px",
    fontWeight: "500",
    lineHeight: "1.4",
    letterSpacing: "0",
    use: "Top-nav menu items",
  },
} as const;

export const claudeRadii = {
  xs: "4px",
  sm: "6px",
  md: "8px",
  lg: "12px",
  xl: "16px",
  pill: "9999px",
  full: "9999px",
} as const;

export const claudeSpacing = {
  xxs: "4px",
  xs: "8px",
  sm: "12px",
  md: "16px",
  lg: "24px",
  xl: "32px",
  xxl: "48px",
  section: "96px",
} as const;

export interface ClaudeComponentMeta {
  key: string;
  name: string;
  description: string;
  category: "Navigation" | "Buttons" | "Cards & Containers" | "Inputs" | "Badges & Tabs" | "Callout & Footer" | "Branding";
  specs: Record<string, string>;
}

export const claudeComponentsRegistry: ClaudeComponentMeta[] = [
  {
    key: "top-nav",
    name: "Top Navigation",
    description: "Cream nav bar pinned to top of page. 64px tall, canvas background, spike mark + wordmark, menu links, Sign in text link, Try Claude coral CTA.",
    category: "Navigation",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      typography: "{typography.nav-link}",
      height: "64px",
    },
  },
  {
    key: "button-primary",
    name: "Primary Button",
    description: "The signature coral CTA. Background coral #cc785c, white text, 40px height, 12px 20px padding, rounded 8px.",
    category: "Buttons",
    specs: {
      backgroundColor: "{colors.primary}",
      textColor: "{colors.on-primary}",
      typography: "{typography.button}",
      rounded: "{rounded.md}",
      padding: "12px 20px",
      height: "40px",
    },
  },
  {
    key: "button-primary-active",
    name: "Primary Button (Active / Press)",
    description: "Active press state variant darkening to coral-active #a9583e.",
    category: "Buttons",
    specs: {
      backgroundColor: "{colors.primary-active}",
      textColor: "{colors.on-primary}",
      rounded: "{rounded.md}",
    },
  },
  {
    key: "button-primary-disabled",
    name: "Primary Button (Disabled)",
    description: "Desaturated cream-tinted disabled state with muted text.",
    category: "Buttons",
    specs: {
      backgroundColor: "{colors.primary-disabled}",
      textColor: "{colors.muted}",
      rounded: "{rounded.md}",
    },
  },
  {
    key: "button-secondary",
    name: "Secondary Button",
    description: "Cream button with 1px hairline border, ink text, matching height and radius.",
    category: "Buttons",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      border: "1px solid {colors.hairline}",
      typography: "{typography.button}",
      rounded: "{rounded.md}",
      padding: "12px 20px",
      height: "40px",
    },
  },
  {
    key: "button-secondary-on-dark",
    name: "Secondary Button (On Dark)",
    description: "Used over dark surface cards. Surface-dark-elevated #252320 background, on-dark text.",
    category: "Buttons",
    specs: {
      backgroundColor: "{colors.surface-dark-elevated}",
      textColor: "{colors.on-dark}",
      typography: "{typography.button}",
      rounded: "{rounded.md}",
      padding: "12px 20px",
    },
  },
  {
    key: "button-text-link",
    name: "Button Text Link",
    description: "Inline text button without background. Used for Sign in and inline actions.",
    category: "Buttons",
    specs: {
      backgroundColor: "transparent",
      textColor: "{colors.ink}",
      typography: "{typography.button}",
    },
  },
  {
    key: "button-icon-circular",
    name: "Circular Icon Button",
    description: "36px circular button with canvas background and hairline border.",
    category: "Buttons",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      border: "1px solid {colors.hairline}",
      rounded: "{rounded.full}",
      size: "36px",
    },
  },
  {
    key: "text-link",
    name: "Inline Text Link",
    description: "Distinctive coral body link, underlined on hover/press.",
    category: "Buttons",
    specs: {
      backgroundColor: "transparent",
      textColor: "{colors.primary}",
      typography: "{typography.body-md}",
    },
  },
  {
    key: "hero-band",
    name: "Hero Band",
    description: "Cream-canvas hero with 6-6 grid, 96px padding, Copernicus display-xl headline, and action cluster.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      typography: "{typography.display-xl}",
      padding: "96px",
    },
  },
  {
    key: "hero-illustration-card",
    name: "Hero Illustration Card",
    description: "Large container holding hero line-art artifact or dark code editor mockup. Rounded 16px.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      rounded: "{rounded.xl}",
      border: "1px solid {colors.hairline}",
    },
  },
  {
    key: "feature-card",
    name: "Feature Card",
    description: "Used in 3-up grids. Surface-card #efe9de background, rounded 12px, generous 32px padding.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.surface-card}",
      textColor: "{colors.ink}",
      typography: "{typography.title-md}",
      rounded: "{rounded.lg}",
      padding: "32px",
    },
  },
  {
    key: "product-mockup-card-dark",
    name: "Product Mockup Card (Dark)",
    description: "Dark navy card showing actual Claude product chrome (chat interface, model output). Rounded 12px, 32px padding.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.surface-dark}",
      textColor: "{colors.on-dark}",
      typography: "{typography.title-md}",
      rounded: "{rounded.lg}",
      padding: "32px",
    },
  },
  {
    key: "code-window-card",
    name: "Code Window Card",
    description: "Signature visual element with dark chrome, inner dark-soft block, JetBrains Mono code, line numbers.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.surface-dark}",
      textColor: "{colors.on-dark}",
      typography: "{typography.code}",
      rounded: "{rounded.lg}",
      padding: "24px",
    },
  },
  {
    key: "model-comparison-card",
    name: "Model Comparison Card",
    description: "Homepage model selector comparing Opus, Sonnet, and Haiku. Canvas background with hairline border.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      typography: "{typography.title-md}",
      rounded: "{rounded.lg}",
      padding: "32px",
    },
  },
  {
    key: "pricing-tier-card",
    name: "Pricing Tier Card",
    description: "Standard tier card on cream canvas with Copernicus serif display-sm price tag and feature checklist.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      typography: "{typography.title-lg}",
      rounded: "{rounded.lg}",
      padding: "32px",
    },
  },
  {
    key: "pricing-tier-card-featured",
    name: "Featured Pricing Tier Card",
    description: "Featured tier flipping to dark surface #181715. The dark surface IS the featured signal.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.surface-dark}",
      textColor: "{colors.on-dark}",
      typography: "{typography.title-lg}",
      rounded: "{rounded.lg}",
      padding: "32px",
    },
  },
  {
    key: "callout-card-coral",
    name: "Callout Card (Coral Full-Bleed)",
    description: "Signature high-voltage coral banner with white text, 48px padding, and inverted cream button.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.primary}",
      textColor: "{colors.on-primary}",
      typography: "{typography.title-md}",
      rounded: "{rounded.lg}",
      padding: "48px",
    },
  },
  {
    key: "connector-tile",
    name: "Connector Tile",
    description: "Integration grid tile on cream canvas with 1px hairline border, logo, and 20px padding.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      typography: "{typography.title-sm}",
      rounded: "{rounded.lg}",
      padding: "20px",
    },
  },
  {
    key: "text-input",
    name: "Text Input",
    description: "Standard 40px input on cream canvas with 1px hairline border and 10px 14px padding.",
    category: "Inputs",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      border: "1px solid {colors.hairline}",
      typography: "{typography.body-md}",
      rounded: "{rounded.md}",
      padding: "10px 14px",
      height: "40px",
    },
  },
  {
    key: "text-input-focused",
    name: "Text Input (Focused)",
    description: "Active focus state featuring 1px coral border and 3px coral outer ring at 15% opacity.",
    category: "Inputs",
    specs: {
      backgroundColor: "{colors.canvas}",
      textColor: "{colors.ink}",
      border: "1px solid {colors.primary}",
      ring: "3px rgba(204,120,92,0.15)",
      rounded: "{rounded.md}",
    },
  },
  {
    key: "cookie-consent-card",
    name: "Cookie Consent Card",
    description: "Floating surface-dark bottom-right notification card with cream text and actions.",
    category: "Cards & Containers",
    specs: {
      backgroundColor: "{colors.surface-dark}",
      textColor: "{colors.on-dark}",
      typography: "{typography.body-sm}",
      rounded: "{rounded.lg}",
      padding: "24px",
    },
  },
  {
    key: "category-tab",
    name: "Category Tab (Inactive)",
    description: "Sub-navigation tab with transparent background and muted text.",
    category: "Badges & Tabs",
    specs: {
      backgroundColor: "transparent",
      textColor: "{colors.muted}",
      typography: "{typography.nav-link}",
      padding: "8px 14px",
      rounded: "{rounded.md}",
    },
  },
  {
    key: "category-tab-active",
    name: "Category Tab (Active)",
    description: "Selected category tab with surface-card background and ink text.",
    category: "Badges & Tabs",
    specs: {
      backgroundColor: "{colors.surface-card}",
      textColor: "{colors.ink}",
      typography: "{typography.nav-link}",
      rounded: "{rounded.md}",
    },
  },
  {
    key: "badge-pill",
    name: "Badge Pill (Cream)",
    description: "Small pill badge with surface-card background and 13px caption typography.",
    category: "Badges & Tabs",
    specs: {
      backgroundColor: "{colors.surface-card}",
      textColor: "{colors.ink}",
      typography: "{typography.caption}",
      rounded: "{rounded.pill}",
      padding: "4px 12px",
    },
  },
  {
    key: "badge-coral",
    name: "Badge Coral (Highlight)",
    description: "Coral pill badge for NEW/BETA tags with uppercase 12px type and 1.5px tracking.",
    category: "Badges & Tabs",
    specs: {
      backgroundColor: "{colors.primary}",
      textColor: "{colors.on-primary}",
      typography: "{typography.caption-uppercase}",
      rounded: "{rounded.pill}",
      padding: "4px 12px",
    },
  },
  {
    key: "cta-band-coral",
    name: "CTA Band (Coral)",
    description: "Full-width pre-footer coral band with Copernicus display-sm headline and cream button.",
    category: "Callout & Footer",
    specs: {
      backgroundColor: "{colors.primary}",
      textColor: "{colors.on-primary}",
      typography: "{typography.display-sm}",
      rounded: "{rounded.lg}",
      padding: "64px",
    },
  },
  {
    key: "cta-band-dark",
    name: "CTA Band (Dark)",
    description: "Dark navy pre-footer band for developer pages with on-dark typography.",
    category: "Callout & Footer",
    specs: {
      backgroundColor: "{colors.surface-dark}",
      textColor: "{colors.on-dark}",
      typography: "{typography.display-sm}",
      rounded: "{rounded.lg}",
      padding: "64px",
    },
  },
  {
    key: "footer",
    name: "Footer",
    description: "Dark navy footer with on-dark-soft typography, Anthropic mark, 4 link columns, 64px vertical padding.",
    category: "Callout & Footer",
    specs: {
      backgroundColor: "{colors.surface-dark}",
      textColor: "{colors.on-dark-soft}",
      typography: "{typography.body-sm}",
      padding: "64px",
    },
  },
  {
    key: "anthropic-mark",
    name: "Anthropic Radial-Spike Mark & Wordmark",
    description: "The signature 4-spoke radial black mark that prefixes the Claude wordmark and anchors the brand.",
    category: "Branding",
    specs: {
      markColor: "{colors.ink}",
      accentColor: "{colors.primary}",
      proportions: "4-spoke radial asterisk geometry",
    },
  },
];
